### ISSUE TITLE
Do not unescape &lt; and &gt; in XML output

### ISSUE THREAD

**Issue by ehenneken** [adsabs/ADSIngestParser#126]
**Describe the bug**
Reference data has been created where &lt; and &gt; in the original data were unescaped into < and >, making the XML invalid. 

**To Reproduce**
Example:
```
grep sref18 /proj/ads/references/sources/ACCR/0014/2023ACCR...14..691W.elsevier.xml 
<sb:reference id="sref18"><sb:contribution langtype="en"><sb:authors><sb:author><ce:given-name>I.G.</ce:given-name><ce:surname>Rigor</ce:surname></sb:author><sb:author><ce:given-name>J.M.</ce:given-name><ce:surname>Wallace</ce:surname></sb:author><sb:author><ce:given-name>R.L.</ce:given-name><ce:surname>Colony</ce:surname></sb:author></sb:authors><sb:title><sb:maintitle>Response of sea ice to the Arctic oscillation</sb:maintitle></sb:title></sb:contribution><sb:host><sb:issue><sb:series><sb:title><sb:maintitle>J. Clim.</sb:maintitle></sb:title><sb:volume-nr>15</sb:volume-nr></sb:series><sb:date>2002</sb:date></sb:issue><sb:pages><sb:first-page>2648</sb:first-page><sb:last-page>2663</sb:last-page></sb:pages><ce:doi>10.1175/1520-0442(2002)015<2648:ROSITT>2.0.CO;2</ce:doi></sb:host></sb:reference>
```

**Additional context**
The `html.unescape()` function causes this behavior

**Comment by seasidesparrow** [comment]
I believe we currently only put raw xml from the input document in the references field.  One simple fix is to modify base parser's '_entity_convert' method to ignore self.base_metadata["references"].

Buf if, in the future, we start to use the fulltext field in ingest_data_model, we may have to think about this more.

@ehenneken have you noticed whether we've parsed documents themselves that have `<>` in the DOI, and if so is it going into the document's "doi" field correctly?
